### ISSUE TITLE
Time Zone Maths

### ISSUE THREAD

**Issue by charudatt** [lu7did/RDX-rp2040#22]
Time Zone Math does not take decimals. eg. +5.3

**Comment by lu7did** [comment]
This issue is still open.

**Comment by lu7did** [comment]
Build 92 includes a fix for this issue.

**Comment by charudatt** [comment]
It does not work, the time difference between UTC and IST (Indian Standard Time) is +5.30.

 

After making changes in the code I get a difference of 12 mins late

 

regards

charudatt vu2upx

**Comment by charudatt** [comment]
It does not work

 

What the debug(Serial Monitor) window shows

 

[10:43:24] @setup Z=10:43 TZ=05:18 Local=16:01

 

What Changes I make in the code –

 

#define TIMEZONE   +5.50    //Buenos Aires, Argentina (GMT-3), change it accordingly using a fractional format VU-Land would be +5.50

 

Actual difference is +5.30 hrs.

 

regards

charudatt – VU2UPX

**Comment by CT7ABA** [comment]
New Version shows local time at monitor instead of UTC

73 de CT7ABA
